import streamlit as st
st.title("Contact Information")
st.title("Interactive Feedback Form")
st.text_input("Name")
st.text_input("Email")
st.text_input("Enter Mobile Number")
st.text_area("Your Message")
if st.button("Submit"):
 st.success("successfully registered.")
st.balloons()
st.write("Thank you for reaching out to us! We will get back to you shortly.")
st.write("For any inquiries, please contact us at:")
st.write("Email: info@tkrec.edu.in")
st.write("Phone: +91-40-12345678")
st.write("Address: TKR Engineering College, Hyderabad, India")
st.write("Follow us on social media for updates and news:")
st.write("Facebook: facebook.com/tkrec")
st.write("Twitter: twitter.com/tkrec")
st.write("LinkedIn: linkedin.com/company/tkrec")
st.write("We look forward to hearing from you!")
