import streamlit as st
st.title("Bio data")
st.write("Name: k.srilatha")
st.write("Age: 36")
st.write("Gender: Female")
st.write("Country: India")
st.write("Education: M.Tech in computer science")
st.write("Profession: Assistant Professor in computer science")
st.write("Hobbies: reading books, cooking, gardening")
st.write("Favorite Food: biryani, sweets")
st.write("Favorite Movie: Inception, The Shawshank Redemption")
st.header("Contact Information")
st.write("Email: k.srilatha@example.com")
st.write("Phone: +91-9876543210")
st.image("https://example.com/profile_picture.jpg", caption="Profile Picture")