import streamlit as st
st.title("Student Registration Form ")
st.text_input("Enter student name")
st.text_input("Enter student age")
st.text_input("Enter student email")
st.time_input("Enter student time")
st.text_input("Enter student address" )
st.selectbox("gender",["male", "female", "other"])
st.text_input("Enter student phone number") 
st.text_input("Enter student course")
st.text_input("Enter student branch")   
st.text_input("Enter student college name")
st.text_input("Enter student university name")
st.text_input("Enter student roll number")
st.text_input("Enter student registration number")
st.text_input("Enter student password") 
st.text_input("Enter student confirm password")
st.button("Submit")
st.button("Reset")
st.button("Update")
st.button("Delete")
st.success("Form submitted successfully!")
st.balloons()
st.write("Thank you for registering!")